//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinkgate.Controls.Assessment {
    
    
    public partial class AssessmentAddendums {
        
        /// <summary>
        /// barchart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Charts.BarChart barchart1;
        
        /// <summary>
        /// barchart2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Charts.BarChart barchart2;
    }
}
