//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinkgate.Controls.Reports {
    
    
    public partial class CompetencyTrackingReportPage {
        
        /// <summary>
        /// SearchAndClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.SearchAndClear SearchAndClear;
        
        /// <summary>
        /// cmbViewBy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AutoCompleteCriteriaControls.ACDropDownList cmbViewBy;
        
        /// <summary>
        /// cmbSchool control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AutoCompleteCriteriaControls.ACDropDownList cmbSchool;
        
        /// <summary>
        /// cmbTeacherName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AutoCompleteCriteriaControls.ACDropDownList cmbTeacherName;
        
        /// <summary>
        /// cmbClass control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DropDownList cmbClass;
        
        /// <summary>
        /// cmbStudent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AutoCompleteCriteriaControls.ACDropDownList cmbStudent;
        
        /// <summary>
        /// cmbDemos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AutoCompleteCriteriaControls.ACDropDownList cmbDemos;
        
        /// <summary>
        /// cmbGroup control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AutoCompleteCriteriaControls.ACDropDownList cmbGroup;
        
        /// <summary>
        /// cmbStandardList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.RadDropDownList cmbStandardList;
        
        /// <summary>
        /// cmbTeacher control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AutoCompleteCriteriaControls.ACSchoolTeacher cmbTeacher;
        
        /// <summary>
        /// cmbStandardSet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AutoCompleteCriteriaControls.GetGradeSubjectCourseStandard cmbStandardSet;
        
        /// <summary>
        /// cmbCompentencyList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.RadDropDownList cmbCompentencyList;
        
        /// <summary>
        /// cmbCompentencyWorksheet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.RadDropDownList cmbCompentencyWorksheet;
        
        /// <summary>
        /// cmbStandardLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.RadDropDownList cmbStandardLevel;
        
        /// <summary>
        /// drDateRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DateRange drDateRange;
        
        /// <summary>
        /// btnExportExcel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btnExportExcel;
        
        /// <summary>
        /// gridResultsPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel gridResultsPanel;
        
        /// <summary>
        /// radGridResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadGrid radGridResults;
        
        /// <summary>
        /// initialDisplayText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder initialDisplayText;
        
        /// <summary>
        /// lblInitialText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblInitialText;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Thinkgate.SearchMaster Master {
            get {
                return ((Thinkgate.SearchMaster)(base.Master));
            }
        }
    }
}
