//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinkgate.Controls.Reports {
    
    
    public partial class UsageStatisticReport {
        
        /// <summary>
        /// sortSpan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl sortSpan;
        
        /// <summary>
        /// ddlView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadComboBox ddlView;
        
        /// <summary>
        /// exportGridImgBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton exportGridImgBtn;
        
        /// <summary>
        /// flag_yellow_template control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image flag_yellow_template;
        
        /// <summary>
        /// SearchAndClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.SearchAndClear SearchAndClear;
        
        /// <summary>
        /// cmbLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DropDownList cmbLevel;
        
        /// <summary>
        /// CalStartMonthYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.MonthYearCalender CalStartMonthYear;
        
        /// <summary>
        /// CalEndMonthYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.MonthYearCalender CalEndMonthYear;
        
        /// <summary>
        /// cblComponentType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblComponentType;
        
        /// <summary>
        /// ctrlRegionSchoolTypeSchool control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.RegionSchoolTypeSchool ctrlRegionSchoolTypeSchool;
        
        /// <summary>
        /// ctrlUsageGradeSubjectCourse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.UsageReportGradeSubjectCourse ctrlUsageGradeSubjectCourse;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Thinkgate.SearchMaster Master {
            get {
                return ((Thinkgate.SearchMaster)(base.Master));
            }
        }
    }
}
