pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["addendums.htm","Addendums","Addendums Return to Assessment Menu How do I add an addendum? In order to add an addendum, follow these steps: 1. Click Assessment 2. Click the Ad...",""],
["adding_editing_classes.htm","Classes","Classes Return to Support Menu How do I add a new class to the system? In order to add a new class to the system please follow the directions belo...",""],
["adding_editing_staff.htm","Staff","Staff Return to Support Menu How do I add a new user to the system? In order to add new staff members to the system please follow the directions l...",""],
["adding_editing_students.htm","Students","Students Return to Support Menu How do I add a new student to the system? In order to add a new student to the system please follow the directions...",""],
["admin_portal.htm","Administrator Portal","Administrator Portal Return to Data Utilization Menu How do I choose my criteria options now that the curriculum criteria menu option is gone? In ...",""],
["advanced_analysis.htm","Advanced Analysis","Advanced Analysis Return to Data Utilization Menu Pick a section... Advanced Analysis Report Engine ",""],
["assessment.htm","Assessment","Assessment Return to Main Menu Pick a topic... Navigate to the desired topic and click a link to further drill down results. Assessment Tools Blue...",""],
["assessment_administration.htm","Assessment Administration","Assessment Administration Return to Assessment Menu Pick a section... Assessment Administration Clickers Online Testing HALO Scanning PlainPaper S...",""],
["assessment_category.htm","Assessment Category","Assessment Category Return to Assessment Menu Pick a section... Assessment Category District Assessments Classroom Assessments ",""],
["assessment_tools.htm","Assessment Tools","Assessment Tools Return to Assessment Menu Pick a section... Assessment Tools Blueprint Summary ",""],
["blueprint.htm","Blueprint","Blueprints Return to Assessment Menu How do I add a new blueprint? A blueprint cannot be \"added\" to the system, only the shell edited. In the begi...",""],
["classroom_tests.htm","Classroom Assessments","Classroom Assessments Return to Assessment Menu I have administered an assessment and scanned the bubble sheets. Is it possible to reset a student...",""],
["clickers_einstruction_ir__rf__.htm","Clickers (eInstruction IR, RF, Renaissance)","Clickers (eInstruction IR, RF, Renaissance) Return to Assessment Menu What Student Response Systems are supported by the Elements&#8482; Clicker Softwar...",""],
["course_curriculum.htm","Course/Curriculum","Course/Curriculum Return to Support Menu Why can&#39;t classes see the district assessment I just added and proofed? (example: User adds a Reading ass...",""],
["curriculum.htm","Curriculum","Curriculum Return to Main Menu Pick a topic... Navigate to the desired topic and click a link to further drill down results. Standards Library Sta...",""],
["data_analysis.htm","Data Analysis","Data Analysis Return to Data Utilization Menu Pick a section... Data Analysis Administrator Portal Teacher Portal ",""],
["data_loads.htm","Data Loads","Data Loads Return to Support Menu Pick a section... Data Loads Roster/Admin/School Files State Data ",""],
["data_utilization.htm","Data Utilization","Data Utilization Return to Main Menu Pick a topic... Navigate to the desired topic and click a link to further drill down results. Data Analysis A...",""],
["district_tests.htm","District Assessments","District Assessments Return to Assessment Menu Can I proof multiple district tests in a term? Yes, as long as each test is a different test type. ...",""],
["filter.htm","Filter","Filter Return to Curriculum Menu What is a Standards Filter? A Standards Filter is a pre determined list of standards that a user can create to ma...",""],
["halo_scanning.htm","HALO Scanning","HALO Scanning Return to Assessment Menu Coming Soon! The HALO Scanning section of the FAQ is under construction. Please contact your district admi...",""],
["images.htm","Images","Images Return to Assessment Menu How do I add an Image to Elements? In order to add a new image to Elements follow these steps: 1. Click Assessmen...",""],
["instruction.htm","Instruction","Instruction Return to Main Menu Pick a topic... Navigate to the desired topic and click a link to further drill down results. Instructional Planni...",""],
["instructional_planning.htm","Instructional Planning","Instructional Planning Return to Instruction Menu Pick a section... Instructional Planning Pacing Guide Standards Alignment ",""],
["internet_settings.htm","Internet Settings","Internet Settings Return to Main Menu Accessing Elements After entering my user name, password and client ID, then clicking Sign In, nothing happe...",""],
["introduction.htm","Main Menu","Updated: 6/23/2010 Main Menu Where to go... Click on one of the following links to navigate to a specific area and its associated sections and que...",""],
["items.htm","Items","Items Return to Assessment Menu How do I create new items in Elements? To create a new item in Elements, follow these steps: 1. Click Assessment 2...",""],
["item_builder.htm","Item Builder","Item Builder Return to Assessment Menu Pick a section... Item Builder Items Addendums Images Rubrics ",""],
["lesson_plan.htm","Lesson Plan","Lesson Plan Return to Instruction Menu Coming Soon! The Lesson Plan section of the FAQ is under construction. Please contact your district adminis...",""],
["online_testing.htm","Online Testing","Online Testing Return to Assessment Menu What is the recommended procedure for administering a test online? In order to administer an assessment o...",""],
["pacing_guides.htm","Pacing Guide","Pacing Guides Return to Instruction Menu How do I add a new Pacing Guide? A pacing guide cannot be \"added\" to the system, only the shell edited. I...",""],
["performance_levels.htm","Performance Levels","Performance Levels Return to Support Menu Can new performance level sets be added? In order to add a Performance Level Set, follow these steps. Ne...",""],
["plainpaper_scanning_pps.htm","PlainPaper Scanning (PPS)","PlainPaper Scanning (PPS) Return to Assessment Menu How do I obtain the Elements&#8482; Plain Paper Scanning Software? Please contact your district poin...",""],
["plans.htm","Plans","Plans Return to Instruction Menu Pick a section... Plans Unit Plan Lesson Plan ",""],
["report_builder.htm","Report Builder","Report Builder Return to Data Utilization Menu Coming Soon! The Report Builder section of the FAQ is under construction. Please contact your distr...",""],
["report_engine.htm","Report Engine","Report Engine Return to Data Utilization Menu Coming Soon! The Report Engine section of the FAQ is under construction. Please contact your distric...",""],
["resources.htm","Resources","Resources Return to Instruction Menu What kind of resources can I add to Elements&#8482;? There are currently two different types of resources that can ...",""],
["resource_library.htm","Resource Library","Resource Library Return to Instruction Menu Pick a section... Resource Library Resources ",""],
["response_to_intervention.htm","Response to Intervention","Response to Intervention Return to Instruction Menu Pick a section... Response to Intervention Academic ",""],
["roster_admin_school.htm","Roster/Admin/School","Roster/Admin/School Return to Support Menu Roster File What is a Roster File? A roster file is a file that contains all the teacher, student and c...",""],
["rti_academic.htm","Academic","Academic Return to Instruction Menu Coming Soon! The Response to Intervention section of the FAQ is under construction. Please contact your distri...",""],
["rubrics.htm","Rubrics","Rubrics Return to Assessment Menu Coming Soon! The Rubrics section of the FAQ is under construction. Please contact your district administrator or...",""],
["schools.htm","Schools","Schools Return to Support Menu How do I add a new school to the system? In order to add a new school to the system please follow the directions be...",""],
["standards_alignment.htm","Standards Alignment","Standards Alignment Return to Instruction Menu What is a Standards Alignment document? A standards Alignment document is a supplemental document t...",""],
["standards_library.htm","Standards Library","Standards Library Return to Curriculum Menu Pick a section... Standards Library State Standards Standards Filter ",""],
["state.htm","State","State Return to Curriculum Menu What kind of information can I see when searching for state standards? When searching for standards you will be ab...",""],
["state_data.htm","State Data","State Data Return to Support Menu What State Data files can be uploaded? Elements currently support the following state data files: CRCT EOCT GHSG...",""],
["summary.htm","Summary","Summary Return to Assessment Menu What is the Assessment Summary? What data does it show? The assessment summary is a report that shows the number...",""],
["support.htm","Support","Support Return to Main Menu Pick a topic... Navigate to the desired topic and click a link to further drill down results. Data Loads Roster/Admin/...",""],
["teacher_portal.htm","Teacher Portal","Teacher Portal Return to Data Utilization Menu How does a teacher control the criteria for the teacher portal? The teacher&#39;s view of the teacher p...",""],
["unit_plan.htm","Unit Plan","Unit Plan Return to Instruction Menu Coming Soon! The Unit Plan section of the FAQ is under construction. Please contact your district administrat...",""]];
