//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinkgate.Controls.Images {
    
    
    public partial class ImageSearch_ExpandedV2 {
        
        /// <summary>
        /// SortBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.SortBar SortBar;
        
        /// <summary>
        /// SearchAndClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.SearchAndClear SearchAndClear;
        
        /// <summary>
        /// ctrlGradeSubjectCourseStandardSet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.GradeSubjectCourseStandardSet ctrlGradeSubjectCourseStandardSet;
        
        /// <summary>
        /// cblItemBank control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblItemBank;
        
        /// <summary>
        /// ExpirationStatusDateRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.ExpirationStatusAndDateRange ExpirationStatusDateRange;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.TextWithDropdown txtSearch;
        
        /// <summary>
        /// SearchPager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.SearchPager SearchPager;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Thinkgate.SearchMaster Master {
            get {
                return ((Thinkgate.SearchMaster)(base.Master));
            }
        }
    }
}
