//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinkgate.Controls.Items {
    
    
    public partial class ItemSearch {
        
        /// <summary>
        /// flag_yellow_template control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image flag_yellow_template;
        
        /// <summary>
        /// SortBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.SortBar SortBar;
        
        /// <summary>
        /// SearchAndClear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.SearchAndClear SearchAndClear;
        
        /// <summary>
        /// hidRefresh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidRefresh;
        
        /// <summary>
        /// hidItemID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidItemID;
        
        /// <summary>
        /// rtsSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTabStrip rtsSearch;
        
        /// <summary>
        /// rmpSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadMultiPage rmpSearch;
        
        /// <summary>
        /// rpBasic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadPageView rpBasic;
        
        /// <summary>
        /// ctrlGradeSubjectCourseStandardSet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.GradeSubjectCourseStandardSet ctrlGradeSubjectCourseStandardSet;
        
        /// <summary>
        /// cblItemBank control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblItemBank;
        
        /// <summary>
        /// cblItemReservation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblItemReservation;
        
        /// <summary>
        /// cmbStandardFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DropDownList cmbStandardFilter;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.TextWithDropdown txtSearch;
        
        /// <summary>
        /// cmbRatingFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cmbRatingFilter;
        
        /// <summary>
        /// lbl_OTCUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden lbl_OTCUrl;
        
        /// <summary>
        /// rpAdvanced control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadPageView rpAdvanced;
        
        /// <summary>
        /// cblItemType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblItemType;
        
        /// <summary>
        /// cblScoreType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblScoreType;
        
        /// <summary>
        /// ctrlAddendumSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AddendumSearch ctrlAddendumSearch;
        
        /// <summary>
        /// ctrlAddendumType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.AddendumType ctrlAddendumType;
        
        /// <summary>
        /// drCreatedDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DateRange drCreatedDate;
        
        /// <summary>
        /// ExpirationStatusDateRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.ExpirationStatusAndDateRange ExpirationStatusDateRange;
        
        /// <summary>
        /// cblItemReviewStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblItemReviewStatus;
        
        /// <summary>
        /// cblDifficultyIndex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblDifficultyIndex;
        
        /// <summary>
        /// drDifficulty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DifficultyRange drDifficulty;
        
        /// <summary>
        /// cblRigor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cblRigor;
        
        /// <summary>
        /// ddlAnchorItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DropDownList ddlAnchorItem;
        
        /// <summary>
        /// rpLRMI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadPageView rpLRMI;
        
        /// <summary>
        /// cbGradeLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cbGradeLevel;
        
        /// <summary>
        /// cbEducationalSubject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cbEducationalSubject;
        
        /// <summary>
        /// cbLearningResource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cbLearningResource;
        
        /// <summary>
        /// cbEducationalUse control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cbEducationalUse;
        
        /// <summary>
        /// cbEndUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cbEndUser;
        
        /// <summary>
        /// txtCreator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.Text txtCreator;
        
        /// <summary>
        /// txtPublisher control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.Text txtPublisher;
        
        /// <summary>
        /// cmbUsageRight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DropDownList cmbUsageRight;
        
        /// <summary>
        /// cbMediaType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cbMediaType;
        
        /// <summary>
        /// cmbLanguage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DropDownList cmbLanguage;
        
        /// <summary>
        /// cmbAgeAppropriate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.DropDownList cmbAgeAppropriate;
        
        /// <summary>
        /// txtDuration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.Duration txtDuration;
        
        /// <summary>
        /// cmbStandardSet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.StandardGradeSubjectId cmbStandardSet;
        
        /// <summary>
        /// txtTextComplexity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.Text txtTextComplexity;
        
        /// <summary>
        /// txtReadingLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.Text txtReadingLevel;
        
        /// <summary>
        /// cbInteractivity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.CheckBoxList cbInteractivity;
        
        /// <summary>
        /// SearchPager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Thinkgate.Controls.E3Criteria.SearchPager SearchPager;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Thinkgate.SearchMaster Master {
            get {
                return ((Thinkgate.SearchMaster)(base.Master));
            }
        }
    }
}
